### ISSUE TITLE
[Feature Request] Return Plex Media Server version

### ISSUE THREAD

**Issue by barnumbirr** [othalla/plex_exporter#5]
Hello,

would be it be possible for the exporter to return Plex's version?

Cheers.

**Comment by othalla** [comment]
Hey @barnumbirr !
Sorry for this late implementation but this is finally done !
Check out this new release [v1.0.0](https://github.com/othalla/plex_exporter/releases/tag/v1.0.0)

let me know if there is any issue.

**Comment by barnumbirr** [comment]
Heu @othalla ,
that's awesome, thanks 🎉 
P.S: I've updated the dashboard example in #8 to return the Plex Media Server version.
